name: Push Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Relase Type"
        required: true
        default: "SNAPSHOT"
        type: choice
        options:
          - SNAPSHOT
          - RELEASE

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run install of dependencies and linter
        run: npm install && npm run lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check docker version
        run: docker --version
      - name: Check docker compose version
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "--version"
      - name: Run container
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up --build --detach --wait --wait-timeout 30"
      - name: Run tests
        run: NEXT_PUBLIC_API_URL=http://localhost:3000 npm run test
      - name: Stop container
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "kill"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT
      - name: Build and push RELEASE
        if: ${{ inputs.releaseType == 'RELEASE' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mkazinauskas/html-to-x:RELEASE-${{ steps.date.outputs.date }},mkazinauskas/html-to-x:latest
      - name: Build and push not RELEASE
        if: ${{ inputs.releaseType != 'RELEASE' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mkazinauskas/html-to-x:${{ inputs.releaseType }}-${{ steps.date.outputs.date }}
