name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Run install of dependencies and linter
      run: npm install && npm run lint
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3      
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3       
    -
      name: Check docker version
      run: docker --version
    -
      name: Check docker compose version
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: "--version"   
    -
      name: Run container
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: "up --build --detach --wait --wait-timeout 30"   
    - 
      name: Run tests
      run: NEXT_PUBLIC_API_URL=http://localhost:3000 npm run test
    - 
      name: Stop container
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: "kill"   